name: Build ROS 2 Humble on Debian 12 ARM64

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted  # 使用自托管的 runner
    strategy:
      matrix:
        os: [debian-12]
        arch: [arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ROS 2 Humble
      run: |
        # 更新apt并安装必要的依赖
        sudo apt-get update && sudo apt-get install -y \
          locales \
          curl \
          gnupg2 \
          lsb-release

        # 设置locale
        sudo locale-gen en_US en_US.UTF-8
        sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
        export LANG=en_US.UTF-8

        # 添加ROS 2的apt仓库
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        echo "deb [arch=arm64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list

        # 更新apt并安装ROS 2 Humble
        sudo apt-get update && sudo apt-get install -y ros-humble-desktop

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install